Add support for Python 3.6
Also convert to zope.testrunner in tox.ini and .travis.yml because of
the namespace package issue:

```
$ tox -e py36
GLOB sdist-make: //zope.proxy/setup.py
py36 create: //zope.proxy/.tox/py36
py36 installdeps: .[test]
py36 inst: //zope.proxy/.tox/dist/zope.proxy-4.2.1.dev0.zip
py36 installed: appdirs==1.4.3,packaging==16.8,pyparsing==2.2.0,six==1.10.0,zope.component==4.3.0,zope.event==4.2.0,zope.i18nmessageid==4.0.3,zope.interface==4.4.0,zope.location==4.0.3,zope.proxy==4.2.1.dev0,zope.schema==4.4.2,zope.security==4.0.3
py36 runtests: PYTHONHASHSEED='770288004'
py36 runtests: commands[0] | python setup.py -q test -q
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
E
======================================================================
ERROR: proxy (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: proxy
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "//zope.proxy/src/zope/proxy/__init__.py", line 21, in <module>
    from zope.interface import moduleProvides
ModuleNotFoundError: No module named 'zope.interface'
```

Also enable travis pip cache.